name: BlueMap Render & Deploy

on:
  workflow_call:
    inputs:
      # GH Action
      runner_name:
        required: false
        description: "Set the runner name. Default is `ubuntu-latest`"
        type: string
        default: "ubuntu-latest"
      # BlueMap
      bluemap_version:
        required: false
        description: "BlueMap version"
        type: string
        default: "5.2"
      # Misc
      workdir_path:
        required: false
        description: "Bluemap workdir."
        type: string
      maps_list:
        required: false
        description: "Map list, separated by space."
        type: string
    secrets:
      SFTP_HOST_NAME:
        required: true
        description: "SFTP Host Name"
      SFTP_USER_NAME:
        required: true
        description: "SFTP User Name"
      SFTP_PASSWORD:
        required: true
        description: "SFTP Password"

jobs:
  render-deploy:
    name: Render & Deploy
    runs-on: ${{ inputs.runner_name }}

    steps:
      ### Checkout Main & act repo ###
      - name: Checkout Repository - Main
        uses: actions/checkout@v4
      
      - name: Checkout Repository - BlueMap Action
        uses: actions/checkout@v4
        with:
          repository: EfinaProjects/bluemap-action
          path: bluemap-act

      ### Setup require tools ###
      - name: Setup - Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Setup - Temp setup python
        run: |
          sudo apt install python3

      - name: Setup - Java 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Setup - Poetry
        uses: abatilo/actions-poetry@v3

      - name: Setup - Poetry install dependencies
        run: |
          cp bluemap-act/pyproject.toml .
          cp bluemap-act/poetry.lock .
          poetry install

      - name: Setup - BlueMap
        run: |
          wget -O cli.jar https://github.com/BlueMap-Minecraft/BlueMap/releases/download/v${{ inputs.bluemap_version }}/BlueMap-${{ inputs.bluemap_version }}-cli.jar
          java -jar cli.jar -V 
        working-directory: bluemap-act

      ### Download Maps ###
      - name: Poetry - SFTP Download
        run: |
          poetry run python $GITHUB_WORKSPACE/bluemap-act/scripts/sftp_downloader.py
          du -sh Maps
          ls -alh Maps        
        env:
          SFTP_HOST_NAME: ${{ secrets.SFTP_HOST_NAME }}
          SFTP_USER_NAME: ${{ secrets.SFTP_USER_NAME }}
          SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
          MAP_LIST: ${{ inputs.maps_list }}
        working-directory: ${{ inputs.workdir_path }}

      ### Download Maps Cache

      # - name: Publish
      #   uses: South-Paw/action-netlify-cli@v2
      #   with:
      #     args: 'deploy --json --dir \"./public\" --message \"draft [${{ github.sha }}]\"'
      #   env:
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      #     NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
